spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payments-consumers-group
      topic-name: inventory-reservation-topic

  datasource:
    url: jdbc:postgresql://localhost:5432/orderprocessingdb
    username: arjunn
    password:
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: payments_schema


server:
  port: 8083
