spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/orderprocessingdb
    username: arjunn
    password:
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: inventory_schema

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-consumer-group

server:
  port: 8081
